### ISSUE TITLE
Zano pos

### ISSUE THREAD

**Issue by lexar201111** [hyle-team/zano_ui#56]
hello everyone. I need help. Zano pos does not start.

**Comment by lexar201111** [comment]
Starting PoS mining iteration
PoS mining: 1737 iterations finished, status: NOT_FOUND, used 9 entries with total amount

**Comment by cryptozoidberg** [comment]
@lexar201111  this messages means that PoS actually works fine, every few seconds it iterates over all your wallet outputs(9 entries in your case) and try to see if it fit to build the block. Reopen if you have more questions!

**Comment by lexar201111** [comment]
Hello. Thank you for responding. and why when the daemon is running it does not show new blocks? that is,"2022-Dec-26 21:09:22.076108 [P2P5][213.91.128.133:11121 OUT][REQUEST_MISSING_OBJECTS]: SYNCHRONIZED OK
2022-Dec-26 21:09:30.279186 [P2P9]Synchronized set to TRUE (5 of 8 con. synced)" is this normal?

**Comment by lexar201111** [comment]
2022-Dec-26 21:12:25.499983 [RPC0][W:ZxCwtB] Starting PoS mining iteration
2022-Dec-26 21:12:25.511985 [RPC0][W:ZxCwtB] PoS mining: 2187 iterations finished, status: NOT_FOUND, used 9 entries with total amount: 18.4682243
2022-Dec-26 21:12:27.527503 [RPC0]wallet RPC idle: refreshing...
2022-Dec-26 21:12:27.529354 [RPC0][W:ZxCwtB] [PULL BLOCKS] 1905847 --> 1905847
2022-Dec-26 21:12:27.530280 [RPC0][W:ZxCwtB] Refresh done, blocks received: 0, balance: 18.468224300000, unlocked: 18.468224300000
2022-Dec-26 21:12:27.530280 [RPC0]wallet RPC idle: scanning tx pool... Is this how it should be?

**Comment by lexar201111** [comment]
Hello. Thank you for responding. and why when the daemon is running it does not show new blocks? that is,"2022-Dec-26 21:09:22.076108 [P2P5][213.91.128.133:11121 OUT][REQUEST_MISSING_OBJECTS]: SYNCHRONIZED OK
2022-Dec-26 21:09:30.279186 [P2P9]Synchronized set to TRUE (5 of 8 con. synced)" is this normal?
 
2022-Dec-26 21:12:25.499983 [RPC0][W:ZxCwtB] Starting PoS mining iteration
2022-Dec-26 21:12:25.511985 [RPC0][W:ZxCwtB] PoS mining: 2187 iterations finished, status: NOT_FOUND, used 9 entries with total amount: 18.4682243
2022-Dec-26 21:12:27.527503 [RPC0]wallet RPC idle: refreshing...
2022-Dec-26 21:12:27.529354 [RPC0][W:ZxCwtB] [PULL BLOCKS] 1905847 --> 1905847
2022-Dec-26 21:12:27.530280 [RPC0][W:ZxCwtB] Refresh done, blocks received: 0, balance: 18.468224300000, unlocked: 18.468224300000
2022-Dec-26 21:12:27.530280 [RPC0]wallet RPC idle: scanning tx pool... Is this how it should be? 
>Понедельник, 26 декабря 2022, 20:49 +07:00 от cryptozoidberg ***@***.***>:
> 
> 
>Closed  #56 as completed.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <hyle-team/zano_ui/issue/56/issue_event/8111449496 @ github . com> 
 
 
--
алексей дайбов
Отправлено из Почты  Mail.ru

**Comment by cryptozoidberg** [comment]
@lexar201111 probably because your wallet didn't make ones yet, it might take some time, depends of the balance.
