### ISSUE TITLE
Disable "Staking" button for wallets with a balance of zero

### ISSUE THREAD

**Issue by OrsonJ** [hyle-team/zano_ui#7]
As reported by [@lilohtanivert](https://twitter.com/lilohtanivert/status/1430584404196294659?s=20) on Twitter, the "Staking" switch can be toggled on/off even if the wallet is empty.

![image](https://user-images.githubusercontent.com/59993846/130964665-e4f164e2-6632-4646-ac9d-78f0e0a30ea2.png)

It would probably be better to disable it for empty wallets to make sure no one gets the impression they can stake without coins.

**Comment by cryptozoidberg** [comment]
@OrsonJ i would suggest to not disable it, since some people might want to keep this on, if they willing to put money on this address later at some point, so the wallet will start actual staking. Re-open it if you want to get back to this subject
